allow accessing interfaces before setting a config
node-usb/node-usb pull request #377
Opened 2020-08-26 16:26 UTC by mildsunrise

Hi! I'm porting a library that needs to access interfaces (to detach kernel drivers, etc) before calling `device.setConfiguration()`.
`usb` currently doesn't make that possible... I'd suggest a fix like this one.

2020-08-27 11:50 UTC, mildsunrise commented
This is also needed to claim interfaces without setting a configuration.  
As indicated by [libusb documentation](http://libusb.sourceforge.net/api-1.0/libusb_caveats.html#configsel), setting configuration causes a lightweight device reset, which may be undesirable.

2021-05-08 07:39 UTC, thegecko commented
Thanks @mildsunrise. Would you mind outlining a test scenario I can use to try this with?

2021-10-02 17:45 UTC, thegecko requested changes

2021-10-02 17:45 UTC, thegecko commented on usb.js
> -	if (defaultConfig === false) return
I think the logic here may be backwards and the solution is to change this to:

```javascript
if (defaultConfig === true) return
```

2022-03-20 14:35 UTC, thegecko commented
Bump!

2022-03-25 14:56 UTC, thegecko commented
@mildsunrise is this still something you want attention on?

2022-03-25 20:17 UTC, mildsunrise commented
Hey sorry about the silence, I just don't know what to do with this.
This PR attempts to fix some of the issues detailed in #381, but ultimately the problem lies in the API.
Things have changed since I opened this, we now offer the WebUSB API which does not have these issues.

So I think a better approach is to make WebUSB work correctly (right now it doesn't seem to, since it uses the legacy API underneath) and then deprecate (or even freeze) the legacy API. @kevinmehall's comments in #401 seem to point in that direction.

2022-03-26 10:40 UTC, thegecko commented
> and then deprecate (or even freeze) the legacy API

I was wondering if the legacy API should literally be the exposure of choice libusb functions?

One drawback to removing this API is the loss of the non-blocking usb access this allows.

2022-03-26 11:25 UTC, mildsunrise commented
> exposure of choice libusb functions

what does 'choice libusb functions' mean? you mean the bits that are not exposed by WebUSB?

> One drawback to removing this API is the loss of the non-blocking usb access this allows

I'm also having trouble following here, isn't WebUSB also a non-blocking API?

2022-03-27 12:17 UTC, thegecko commented
> what does 'choice libusb functions' mean? you mean the bits that are not exposed by WebUSB?

I mean a raw interface that resembles common, low-level libusb calls.

> I'm also having trouble following here, isn't WebUSB also a non-blocking API?

I believe many of the legacy usb calls (e.g. `getDeviceList()`) return synchronous data from the kernel cache. Calls such as requests for strings need to interrogate the device so are async/blocking.

As WebUSB needs a lot of data loaded up to satisfy the device model, there's a lot more device access.

2022-03-27 13:51 UTC, mildsunrise commented
Ah, I see. Well... if we could go back in the past, I do agree that the legacy API should've just been a raw interface to libusb, with very little "magic".

But well, we ended up with this, and I think adding it now (either as a 3rd API, or by removing the current legacy API) would confuse users more. Maybe we could extend WebUSB with the libusb-specific bits it lacks? WebUSB looks close to a raw interface, we'd only have to give the option to disable the 'high-level' behaviour (basically the loading of string descriptors?)

2022-04-02 19:01 UTC, thegecko commented
OK, lets keep the legacy API (perhaps it should be called `raw` API?). I'm reluctant to extend the WebUSB API too much as it's already a standard and introduces incompatibility with the browser implementations.

> ...a better approach is to make WebUSB work correctly (right now it doesn't seem to...

Would you mind outlining how this doesn't work in a little more detail. Perhaps expanding #381 a little more with specific cases?

2022-04-02 19:04 UTC, thegecko commented
I'll close this for now and attack #381 issues considering the WebUSB API too.

2022-04-02 19:04 UTC, closed without merging